# Generated by Django 5.0.4 on 2024-04-12 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
