# Generated by Django 4.2.7 on 2024-04-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_like_post_remove_like_user_delete_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/defaultImg/default_pic.jpg', null=True, upload_to='media/profile/'),
        ),
    ]
